name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: okteto/context@2.7.0
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: Deploy
        uses: okteto/pipeline@2.7.0
        with:
          name: sergionamespace # cambiar por su namespace
          timeout: 5m

